export declare type Vacancy = {
  vacancy_id: string;
  tenant_id: string | null;
  vacancy_name: string | null;
  tenant_name: string | null;
  vacancy_base_url: string | null;
  jenjang: string | null;
  stream_name: string | null;
  jurusan_name: string | null;
  jurusan_filter_type: string | null;
  total_job_available: string | null;
  check_certificate: string | null;
  major_group_non_sma: string | null;
  major_group_sma: string | null;
  allow_sma: string | null;
  highest_age_sma: string | null;
  lowest_ipk_sma: string | null;
  allow_d3: string | null;
  highest_age_d3: string | null;
  lowest_ipk_d3: string | null;
  allow_s1: string | null;
  highest_age_s1: string | null;
  lowest_ipk_s1: string | null;
  allow_s2: string | null;
  highest_age_s2: string | null;
  lowest_ipk_s2: string | null;
  vacancy_type: string | null;
  major_sma_custom: string | null;
  major_non_sma_custom: string | null;
};

export declare type VacancyDetail = {
  vacancy_id: string;
  tenant_name: string;
  no_ig: string | undefined;
  vacancy_name: string;
  vacancy_type: string;
  vacancy_requirements: string;
  vacancy_description: string;
  logo: string | undefined;
  list_province_text: null;
  quota: string;
  applied: null;
  job_function: string;
  major_education_filter_type: string;
  jenis_kelamin: string;
  kota_penempatan: null;
  employee_type_vac: string;
  check_certificate: string;
  list_certificate: null;
  major_group_non_sma: string;
  major_group_sma: string;
  allow_sma: string;
  highest_age_sma: null;
  lowest_ipk_sma: null;
  allow_d3: string;
  highest_age_d3: null;
  lowest_ipk_d3: null;
  allow_s1: string;
  highest_age_s1: string;
  lowest_ipk_s1: string;
  allow_s2: string;
  highest_age_s2: null;
  lowest_ipk_s2: null;
};
